### ISSUE TITLE
Redirecting to https://typograf.vercel.app/api/process

### ISSUE THREAD

**Issue by denostr** [vandesign/alfred-detoxit#3]
Когда вызываю команду, приходит алерт что все отработало, но в буфере вместо исправленного текста содержиится следующее
> Redirecting to https://typograf.vercel.app/api/process (308)

**Comment by vandesign** [comment]
Привет! Обнови воркфлоу, вроде я чинил это.

**Comment by denostr** [comment]
Стоит последняя версия 0.0.2
Попробовал удалить и поставить заново, не помогло(

**Comment by vandesign** [comment]
Тогда попробуй сходить в сам Типограф. Может на их стороне что-то https://github.com/typograf/typograf

**Comment by tplk** [comment]
@vandesign в ветке `master` есть нужные правки, но релиза не было. Нужно создать тег `0.0.3`, чтобы релиз появился.

@denostr можешь установить актуальный воркфлоу отсюда: https://github.com/vandesign/alfred-detoxit/raw/master/Detoxit!.alfredworkflow

**Comment by denostr** [comment]
@tplk спасибо, это помогло!

**Comment by vandesign** [comment]
Вроде пофиксил ) Спасибо, @tplk
